# Numpy

In [ ]:
# pip install numpy

In [ ]:
import numpy as np

## Numpy Create Array

In [ ]:
#@title 0-D Array

var_array = np.array(42)

print(var_array)

42


In [ ]:
#@title 1-D Array

var_array = np.array([1, 2, 3, 4, 5])

print(var_array)

[1 2 3 4 5]


In [ ]:
var_array = np.ones(5) #output angka satu
print(var_array)

[1. 1. 1. 1. 1.]


In [ ]:
var_array = np.zeros(4) #output angka nol
print(var_array)

[0. 0. 0. 0.]


In [ ]:
var_array = np.random.random(6) #output angka secara random
print(var_array)

[0.2517622  0.06860088 0.86215751 0.65284615 0.71573341 0.48271725]


In [ ]:
#@title 2-D Array

var_array = np.array([[1, 2, 3], [4, 5, 6]])

print(var_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
#@title 3-D Array

var_array = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(var_array)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
#@title Check dimensi array = .ndim

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
#@title Create array range
#numpy.arange(start, stop, step)

var_array = np.arange(1, 20, 2)
print(var_array)

[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
# create with reshape
var_array = np.arange(10).reshape((2, 5)) #var_array = np.arange(0:10)
print(var_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
# create numpy text

var_array = np.array(['apple', 'banana', 'cherry'])
print(var_array)

['apple' 'banana' 'cherry']


## Numpy Array Indexing

In [ ]:
#@title Akses indeks

# 1-D
var_array = np.array([85, 55, 40, 90])

# mengakses data pada array
print(var_array[3])

90


In [ ]:
# 2-D
var_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
# 0 = [1,2,3,4,5]
# 1 = [6,7,8,9,10]
print(var_array[1, 2]) #[baris,kolom]

8


In [ ]:
# 3-D
var_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(var_array[1, 1, 2]) #print(var_array[1:2, :2, 2])

12


In [ ]:
#@title Operation indeks

var_array = np.array([1, 2, 3, 4])

print(var_array[2] + var_array[3])

7


In [ ]:
print(var_array[0] + var_array[2])

4


In [ ]:
#@title Slicing array

# 1-D
var_array = np.array([1, 2, 3, 4, 5, 6, 7])

print(var_array[3:])

[4 5 6 7]


In [ ]:
# 2-D
var_array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(var_array[0, 1:4])

[2 3 4]


In [ ]:
# 3-D
var_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(var_array[1, 1, 0:2])

[10 11]


In [ ]:
#@title Iterating Arrays

var_array = np.array([1, 2, 3])

for x in var_array:
  print(x)

1
2
3


In [ ]:
var_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in var_array:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


## Numpy Array Join

In [ ]:
#@title Concatenate

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
var_array1 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
var_array2 = np.array([[[4, 7, 9], [1, 6, 2]], [[3, 5, 8], [19, 10, 14]]])

arr = np.concatenate((var_array1, var_array2))
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[ 4  7  9]
  [ 1  6  2]]

 [[ 3  5  8]
  [19 10 14]]]


In [ ]:
#@title Stack = bertumpuk

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# arr = np.stack((arr1, arr2)) #biasa
# arr = np.hstack((arr1, arr2)) #horizontal, satu dimensi kolom ke samping
# arr = np.vstack((arr1, arr2)) #vertical, satu dimensi kolom kebawah
arr = np.dstack((arr1, arr2)) # #dimension

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


## Numpy Splitting

In [ ]:
# 1-D
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)

print(newarr)
#output = [array([1, 2]), array([3, 4]), array([5, 6])]

In [ ]:
# 2-D
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
# 3-D
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
newarr = np.array_split(arr, 2)

print(newarr)

[array([[[1, 2, 3],
        [4, 5, 6]]]), array([[[1, 2, 3],
        [4, 5, 6]]])]


## Numpy Matriks

In [ ]:
matriks = [[1,2,3],
           [4,5,6],
           [7,8,9]]

matrik_np = np.array(matriks)
print(matrik_np)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#@title Operasi matrik

matrik_a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

matrik_b = np.array([
    [3, 2, 1],
    [6, 5, 4],
    [9, 8, 7]])


hasil = matrik_a + matrik_b
print("Hasil Penjumlahan:")
print(hasil)

Hasil Penjumlahan:
[[ 4  4  4]
 [10 10 10]
 [16 16 16]]


In [ ]:
hasil = matrik_a - matrik_b
print("Hasil Pengurangan:")
print(hasil)

Hasil Pengurangan:
[[-2  0  2]
 [-2  0  2]
 [-2  0  2]]


In [ ]:
# pangkat dengan power()

result_power = np.power(matrik_a, 2)
print("Hasil Perhitungan Pangkat (matrik_a pangkat 2):")
print(result_power)

Hasil Perhitungan Pangkat (matrik_a pangkat 2):
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [ ]:
# trigonometri dengan sin()

result_power = np.sin(matrik_a)
print("Hasil sin matrik_a:")
print(result_power)

Hasil sin matrik_a:
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]


In [ ]:
#@title Transpose matrik

matrik_a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

print("Matrik awal: ")
print(matrik_a)


hasil = matrik_a.transpose()
print("\nMatrik kebalikan: ")
print(hasil)

Matrik awal: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrik kebalikan: 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
#@title Reshape matrik

matrik_a = np.array([1, 2, 3, 4, 5, 6])

print("Matrik awal: ")
print(matrik_a)
print("Ukuran = ", matrik_a.shape) #shape = membaca baris dan kolom

# mengubah ukran ke 3x2
hasil = matrik_a.reshape(3, 2)

print("\nMengubah ke 3x2: ")
print(hasil)
print("Ukuran = ", hasil.shape)

Matrik awal: 
[1 2 3 4 5 6]
Ukuran =  (6,)

Mengubah ke 3x2: 
[[1 2]
 [3 4]
 [5 6]]
Ukuran =  (3, 2)


In [ ]:
#@title Matrik flatten = menjadi 1d horizontal

matrik_a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

print("Matrik awal: ")
print(matrik_a)
print("Ukuran = ", matrik_a.shape)

hasil = matrik_a.flatten()

print("\nMatrik setelah di-flatten: ")
print(hasil)
print("Ukuran = ", hasil.shape)

Matrik awal: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Ukuran =  (3, 3)

Matrik setelah di-flatten: 
[1 2 3 4 5 6 7 8 9]
Ukuran =  (9,)


## Numpy Statistik

In [ ]:
#@title rata-rata (mean)

data = np.array([12, 15, 18, 22, 30, 35, 40, 45, 55, 65])

mean = np.mean(data)
print("Rata-rata (mean):", mean)

Rata-rata (mean): 33.7


In [ ]:
#@title median

median = np.median(data)
print("Median:", median)

Median: 32.5


In [ ]:
#@title standard deviation

std_deviation = np.std(data)
print("Deviasi Standar (standard deviation):", std_deviation)

Deviasi Standar (standard deviation): 16.79315336677421


In [ ]:
#@title variansi (variance)

variance = np.var(data)
print("Variansi (variance):", variance)

Variansi (variance): 282.01


In [ ]:
#@title minimum dan maksimum

minimum = np.min(data)
maximum = np.max(data)
print("Nilai Minimum:", minimum)
print("Nilai Maksimum:", maximum)

Nilai Minimum: 12
Nilai Maksimum: 65


In [ ]:
#@title quartile

# Menghitung kuartil pertama (Q1) dan kuartil ketiga (Q3)
q1 = np.percentile(data, 25)
q3 = np.percentile(data, 75)
print("Kuartil Pertama (Q1):", q1)
print("Kuartil Ketiga (Q3):", q3)


# Menghitung rentang interkuartil (IQR)
iqr = q3 - q1
print("Rentang Interkuartil (IQR):", iqr)

Kuartil Pertama (Q1): 19.0
Kuartil Ketiga (Q3): 43.75
Rentang Interkuartil (IQR): 24.75


## Soal 1

Buat contoh :

* numpy array (1D, 2D, 3D)
* numpy join
* numpy split
* operasi matrik

In [1]:
import numpy as np
#1
#1d
bilangan_prima = np.array ([2, 3, 5, 7, 11, 13, 17, 19])
print("Bilangan Prima : \n",bilangan_prima)
print('----------------------------------')

#2d
bilangan1 = np.array ([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
bilangan2 = np.array ([[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])
print("Bilangan Pertama : \n", bilangan1)
print("Bilangan Kedua : \n",bilangan2)
print('-----------------------------------')

#3d
bilangan_genap = np.array ([[[2, 4, 6, 8], [12, 14, 16 ,18]], [[22, 24, 26, 28], [32, 34, 36, 38]]])
bilangan_ganjil = np.array ([[[3, 5, 7, 9], [13, 15, 17, 19]], [[23, 25, 27, 29], [33, 35, 37, 39]]])
print("Bilangan Genap : \n", bilangan_genap)
print("Bilangan Ganjil : \n", bilangan_ganjil)
print('-----------------------------------')

#numpy join
join = np.concatenate((bilangan_ganjil, bilangan_genap))
stack = np.hstack((bilangan_ganjil, bilangan_genap))
print("Penggabungan Bilangan Menggunakan Join: \n", join)
print("Penggabungan Bilangan Menggunakan Stack: \n", stack)
print('-----------------------------------')

#numpy split
split_1d = np.array_split(bilangan_prima, 4)
split_2d = np.array_split(bilangan1, 2)
split_3d = np.array_split(bilangan_genap, 2)
print("Split Bilangan 1D: \n", split_1d)
print("Split Bilangan 2D: \n", split_2d)
print("Split Bilangan 3D: \n", split_3d)
print('-----------------------------------')

#operasi matrix
pengurangan = bilangan_ganjil - bilangan_genap
print("Hasil Pengurangan : \n", pengurangan)
penjumlahan = bilangan1 + bilangan2
print("Hasil Pemjumlahan : \n", penjumlahan)
pangkat = np.power(bilangan_prima, 2)
print("Hasil Perhitungan Pangkat : \n", pangkat)
print('-----------------------------------')

Bilangan Prima : 
 [ 2  3  5  7 11 13 17 19]
----------------------------------
Bilangan Pertama : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Bilangan Kedua : 
 [[11 12 13 14 15]
 [16 17 18 19 20]]
-----------------------------------
Bilangan Genap : 
 [[[ 2  4  6  8]
  [12 14 16 18]]

 [[22 24 26 28]
  [32 34 36 38]]]
Bilangan Ganjil : 
 [[[ 3  5  7  9]
  [13 15 17 19]]

 [[23 25 27 29]
  [33 35 37 39]]]
-----------------------------------
Penggabungan Bilangan Menggunakan Join: 
 [[[ 3  5  7  9]
  [13 15 17 19]]

 [[23 25 27 29]
  [33 35 37 39]]

 [[ 2  4  6  8]
  [12 14 16 18]]

 [[22 24 26 28]
  [32 34 36 38]]]
Penggabungan Bilangan Menggunakan Stack: 
 [[[ 3  5  7  9]
  [13 15 17 19]
  [ 2  4  6  8]
  [12 14 16 18]]

 [[23 25 27 29]
  [33 35 37 39]
  [22 24 26 28]
  [32 34 36 38]]]
-----------------------------------
Split Bilangan 1D: 
 [array([2, 3]), array([5, 7]), array([11, 13]), array([17, 19])]
Split Bilangan 2D: 
 [array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]])]
Split

## Soal 2

* Buatlah numpy array dengan matrik ukuran 3x4 dan range array 10-30
* Kemudian lakukan flatten
* cari nilai statistik (mean, median, dsb)

In [2]:
import numpy as np
myMatrix = np.array ([[12, 14, 16, 18],[13, 15,17, 19],[22, 24, 26, 28]])

print("Array 3x4 : \n", myMatrix)

flatten = myMatrix.flatten()
print('')
print("Flattened : ", flatten)
print('')
print('----------------------------')
print('Operation')
print('----------------------------')
print("Mean : ", np.mean(flatten))
print("Median : ", np.median(flatten))
print("Std Deviasi : ", np.std(flatten))
print("Variance : ", np.var(flatten))
print("Min : ", np.min(flatten))
print("Max : ", np.max(flatten))
q1=np.percentile(flatten, 25)
q3=np.percentile(flatten, 75)
print("Quartile 1: ", q1)
print("Quartile 3: ", q3)
print("Interquartile: ", q3-q1)

Array 3x4 : 
 [[12 14 16 18]
 [13 15 17 19]
 [22 24 26 28]]

Flattened :  [12 14 16 18 13 15 17 19 22 24 26 28]

----------------------------
Operation
----------------------------
Mean :  18.666666666666668
Median :  17.5
Std Deviasi :  5.022173057773121
Variance :  25.222222222222218
Min :  12
Max :  28
Quartile 1:  14.75
Quartile 3:  22.5
Interquartile:  7.75
